###################################################################################################
# src/configs/config.yaml: Config file for Hydra.
# Hopefully passes all the important parameters.
# Usage example: python src/main.py --multirun oc.nummode=9,10 wandb=false
project: ENSOTrend-beta
user: sdat2
animate: true # whether to make animations after run.
wandb: true # whether or not to sync to weights and biases.
# name: k_days_${atm.k_days} # name needs to be unique otherwise will overwrite.
name: k_days_${atm.k_days}_eps_days_${atm.eps_days}_e_frac_${atm.e_frac}_c_d_${coup.c_d}_vary_cloud_const_${atm.vary_cloud_const}_${atm.mem}
# name: eps_days_${atm.eps_days}
# python src/main.py --multirun atm.eps_days=1.35,1.45
# python src/main.py --multirun atm.eps_days=0.35,0.45
# python src/main.py --multirun atm.eps_days=1.65
comp:
  htherm: 4c
  sst: 5a
  prwnd: 5a
test: false # unimportant param for filtering later.
atmos: true # run the atmospheric model.
run: true  # whether to run any of the ocean model.
archive: true # whether to move the run to the gws archive
archive_dir: /gws/nopw/j04/ai4er/users/sdat2/ensotrend-beta
ocean: # whether to run parts of the ocean model
  tcom_name: tcom
  tios2cdf_name: tios2cdf
  spin: true
  diag: true
  ingrid: true   # whether to use spin-up step
  run_through: true
  animate_qflx: true
oc: # the ocean paramters
  nummode: 2 # each aditional mode adds about 7 minutes to the run time of run2f.
  boundaries: Periodic # realistically this can't be changed.
  # How long to run each part of the ocean model.
  time_test: 2 months # the time input to the tests.
  time_spin: 20 years # seems long - maybe check that this is the correct number to be quoting.
  time_diag: 2 years # This time period includes the period during which qflx is removed.
  time_run2f: 60 years # 58 years originally
  # editing of hcut and tcut currently disabled just in case.
  hcut: 5
  tcut: 14.6
  f1prime: -0.006 # -0.0021
coup:
  c_d: 2.25e-3    # dimensionless?,  wind stress.
  # breaks ocean model by the time you get to 3.5e0, but probably before.
  rho_air: 1.225   # kg m-3, density of sea surface air
  iterations: 10  # how many times to repeat the coupling.
  # The stopping condition is currently quite qualitative, and so 
  # iterations will be quite hard to tune.
  # Initially when fully coupled the models blew up.
atm:
  # begining TCAM
  prcp_land: 1   # use data precip trends over land
  r: 0.80  # humidity basic value to multiply q_a by.
  h_q: 1800  # Hq is a scale depth for moisture
  wnsp_min: 4 # m s-1
  rho_00: 0.3 # this is the value for rho_bar in the paper rather than rho_00
  # this means the density at the surface.
  # this is actual rho_bar in the paper
  # 0.3 kg m-3
  # Strange properties to plot different models etc.
  mem: "EEEEEEE"  # string is iterated through - standard model uses fixed value for
  # relative humidity.
  # Format: ${ts}${clt}${sfcwind}${rh}${pr}${ps}${tau}
  # mem: "EECC" would be the option close to cmip world.
  # E: ECMWF
  # f: fixed
  # C: CMIP5
  # S or 6: CMIP6
  pr_max_mm_day: 20 # mm per day maximum precip
  relative_humidity: 0.80  # relative humidity uniformly 80%
  number_iterations: 50  #  int, the number of iterations in the atmos solver.
  height_tropopause: 15e3  # metres. I.e 15 km.
  theta_00: 300  # potential temperature at the surface in kelvin.
  nbsq: 3.0e-4  # N^2 s-2. N^2 is a specified buoyancy frequency.
  # from scipy.constants import Stefan_Boltzmann, zero_Celsius
  gravity: 9.8  #  m s-2
  latent_heat_vap: 2.5e6  # latent heat # J kg-1
  cp_air: 1000  #  cp_air is the specific heat capacity of air.
  # J kg-1 K-1
  k_days: 10     # K: 1/10 days, k_days is the recipriocal, and has the units of days.
  # raleigh friction step.
  eps_days: 0.75 # this is the inverse of the raleigh friction coefficient epsilon.
  # Over 1958–2017, the CO2 changed from ~300 to ~400 ppm, which would be about 0.75 W m−2
  # mult_or_div:  * 1 *
  e_frac: 0.5   # multiply epsu by efrac to get epsv
  # e_frac=1/2 in paper
  rho_air: 1.225  # kg m-3 - also called rho_00
  emmisivity: 0.97
  p_s: 1000  # pressure at the surface in mb
  es_0: 6.11 # evaporation
  e_factor: 0.622 # strange constant
  delta_temp: 1.0  # ΔT: 1 K
  f2: 0.05  # f2: 0.05
  # 'a_cloud_const' should decrease when deep convection happens above 28 degC
  #  a_cloud_const: Ts-temp_0_c;a_cloud_const[a_cloud_const>28]: 40;
  # a_cloud_const[a_cloud_const<=28]: 80;
  # a_cloud_const: 0.01*a_cloud_const
  a_cloud_const: 0.6  # this isn't the option used in the paper, but this was in the original code.
  vary_cloud_const: true # whether or not to use variable values instead.
  dc_threshold_temp: 28 # above 28 degrees celsius we might get deep convection 
  a_cloud_const_dc: 0.4   # this is for deep convection
  a_cloud_const_norm: 0.8   # this is for normal conditions
  # basic parameters
  f1_bar: 0.39  # f1 = 0.39
  # f'1  is the anomaly in f1—a parameter that can be adjusted
  # to control the variation in surface longwave radiation due
  # to a_cloud_const change in CO2
  u_bar: 5.0  # average velocity?
  c_bar: 0.6  # C is the cloud cover. perhaps C_bar is the average.
  temp_surface_bar_celsius: 25
  c_e: 0.00125  # 1.25e-3 # cE is an exchange coefficient. Pretty arbritatry, not yet varied.
  nx: 180  # number of x grid boxes
  ny: 60  # this seems like half the grid space
  y_north_lim: 60  # upper lat limit

