###################################################################################################
project: seager19
user: sdat2
run_name: test_13
notes: test hydra, animating files
run: false
ingrid: true
animate: true
