###################################################################################################
# Config file for Hydra:
# hopefully passes all the important parameters.
project: seager19
user: sdat2
name: test_diag1
test: true # unimportant param for filtering later.
notes: test diag fix
run: true  # whether to run any of the ocean model.
ocean:
  tcom_name: tcom
  tios2cdf_name: tios2cdf
  spin: true
  diag: true
  ingrid: false
  run_through: false
coup:
  cd: 2.25e-3  # Pa m-1 s
  rho_a: 1.225  # kg m-3
animate: true
atm:
  eps_days: 0.75
  k_days: 10
  efrac: 2.0    # multiply epsu by efrac to get epsv
  hq: 1800
  prcp_land: 1   # use data precip trends over land
  wnspmin: 4
  rho00: 0.3
  prmax: 20.0 / 3600 / 24
  r: 0.80
  nx: 180
  ny: 60
  YN: 60
  YS: -${atm.YN}
  nbsq: 3.0e-4