# src/configs/sensitivity.yaml
# a file to contain the parameters to sweep through and their ranges
coup.c_d:
 - 1.0e-3
 - 3.0e-3
atm.eps_days:
 - 0.4
 - 1.4
atm.e_frac:
 - 1.9
 - 2.1
atm.k_days:
 - 8
 - 13
