name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v2
    - name: check gfortran
      run: gfortran --version
    - name: check gcc
      run: gcc --version
    - name: install netcdf
      run: sudo apt-get install libnetcdf-dev libnetcdff-dev
    - name: check netcdf
      run: nc-config --all
    - name: make
      run: make
      working-directory: ocean/SRC
    #- name: make check
    #  run: make check
    #- name: make distcheck
    #  run: make distcheck
