name: CI
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "*"
  schedule:
    - cron: "0 13 * * 1"

jobs:
  build:
    name: Build (${{ matrix.python-version }} | ${{ matrix.os }})
    if: github.repository == 'sdat2/seager19'
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-16.04"]
        python-version: ["3.7", "3.8"]
    steps:
      - uses: actions/checkout@v2
      - name: update apt-get
        run: sudo apt-get update
      - name: install netcdf
        run: sudo apt-get install --fix-missing libnetcdf-dev libnetcdff-dev 
      - name: Cache conda
        uses: actions/cache@v2.1.6
        env:
          # Increase this value to reset cache if ci/environment.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('requirements/ci_env.yml') }}
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: test_env_seager19 # Defined in ci/environment*.yml
          auto-update-conda: false
          python-version: ${{ matrix.python-version }}
          environment-file: requirements/ci_env.yml
          use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!
      - name: Set up conda environment
        run: |
          python -m pip install -e . --no-deps
          conda list
      - name: Run Tests
        run: |
          pytest --cov=./src/ --cov-report=xml
      - name: Upload code coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
          flags: unittests
          env_vars: OS,PYTHON
          name: codecov-umbrella
          fail_ci_if_error: false
