name: Fortran/C

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-16.04

    # sudo apt-get install --fix-missing gfortran
    # sudo apt update
    steps:
    - uses: actions/checkout@v2
    - name: update apt-get
      run: sudo apt-get update
    - name: install netcdf
      run: sudo apt-get install --fix-missing libnetcdf-dev libnetcdff-dev 
    - name: check netcdf
      run: nc-config --all
    - name: check gfortran
      run: gfortran --version
    - name: check gcc
      run: gcc --version
    - name: make
      run: make
      working-directory: ocean/SRC
    - name: make tios2cdf
      run: make tios2cdf
      working-directory: ocean/SRC
    - name: make all
      run: make all
      working-directory: ocean/SRC
    # - name: make check
    #   run: make check
    # - name: make distcheck
    #   run: make distcheck
