name: python

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2    
        
      - name: pylinter
        # You may pin to the exact commit or the version.
        # uses: alexanderdamiani/pylinter@f9e3029cf605992791a0ee1b44c152483bc9f3b9
        uses: alexanderdamiani/pylinter@v1.1.0
        with:
          # directory to run linting on
          python-root: src # optional, default is .
          # flake8 flags
          flake8-flags: #src # optional, default is 
          # mypy flags
          mypy-flags: #src # optional, default is 
          # optional exit on isort errors
          fail-on-isort: #src # optional
          # skip flake8 checks
          skip-flake8: #src # optional
          # skip mypy checks
          skip-mypy: #src # optional
          # skip isort checks
          skip-isort: #src # optional
